trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      pip install pandas
    displayName: 'Install dependencies'

  - script: |
      python week5/delay_analysis.py
    displayName: 'Run Delay Analysis'
